name: Stage - Deploy to EC2

on:
  push:
    branches:
      - 'release/stg/**'
      - 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}
      

      - name: Deployment version
        run: |
          echo "Deploying version: ${{ github.sha }}"

      - name: Build and push Docker image
        run: |          
          cd simple-app
          aws ecr get-login-password --region ${{ vars.AWS_REGION }} | docker login --username AWS --password-stdin ${{ vars.ECR_REPO_URL }}
          docker build -t "${{ vars.ECR_REPO }}:latest" .
          docker tag "${{ vars.ECR_REPO }}:latest" "${{ vars.ECR_REPO_URL }}/${{ vars.ECR_REPO }}:latest"
          docker push "${{ vars.ECR_REPO_URL }}/${{ vars.ECR_REPO }}:latest"
