name: Development - Deploy to EC2

on:
  push:
    branches:
      - 'release/stg/**'
      - 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        env:
          ACTIONS_STEP_DEBUG: true
        with:
          role-to-assume: ${{ secrets.AWS_IAM_ROLE_ARN }}
          aws-region: ${{ vars.AWS_REGION }}
      
      - name: Deployment version
        run: |
          echo "Deploying version: ${{ github.sha }}"
      
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push Docker image to Amazon ECR
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: asset-mappr
          SHORT_SHA: "${{ github.sha }} | cut -c 1-7"
          IMAGE_TAG: "FE-DEV-$SHORT_SHA"
        run: |
          cd simple-app
          docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG