name: Dev - Deploy to EC2

on:
  push:
    branches:
      - 'release/dev/**'
      - 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}
      

      - name: Deployment version
        run: |
          echo "Deploying version: ${{ github.sha }}"
      
      - name: Authenticate with Amazon ECR
        run: |
          aws ecr get-login-password --region ${{ vars.AWS_REGION }} | docker login --username AWS --password-stdin ${{ vars.ECR_REPO_URL }}
  

      - name: Build, tag, and push Docker image to Amazon ECR
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: asset-mappr
          SHORT_SHA: "${{ github.sha }} | cut -c 1-7"
          IMAGE_TAG: "FE-DEV-$SHORT_SHA"
        run: |          
          cd simple-app
          SHORT_SHA=$(echo ${{ github.sha }} | cut -c 1-7)
          docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG