name: Stage - Deploy to EC2

on:
  push:
    branches:
      - 'release/stg/**'
      - 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::045399055737:user/github-actions-access
          aws-region: ${{ vars.AWS_REGION }}
      
      - name: Deployment version
        run: |
          echo "Deploying version: ${{ github.sha }}"
      
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push Docker image to Amazon ECR
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: asset-mappr
          IMAGE_TAG: "${{ github.sha }} | cut -c 1-7"
        run: |
          cd simple-app
          docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG
